### ISSUE TITLE
Bot responds for each time a key word is said. if a message contains 3 trigger words, the response is sent 3 times. 

### ISSUE THREAD

**Issue by Bobrobot1** [Bobrobot1/Suicide-Prevention-Bot#1]
Fix to come in later update.

**Comment by gusuu1** [comment]
Suggestion: add a cooldown as well. 

Making sure a user only receives this alert message once per hour/day, no matter how many times they mentioned a keyword, will help to prevent spam and make the alert more meaningful.

**Comment by Killerjet101** [comment]
We have added away so you can have the bot ignore you and not send an alert with "sp!mute" or "sp!ingore". We are also looking into the cooldown when the bot becomes more active.

**Comment by Killerjet101** [comment]
> Suggestion: add a cooldown as well.
> 
> Making sure a user only receives this alert message once per hour/day, no matter how many times they mentioned a keyword, will help to prevent spam and make the alert more meaningful.

We have added away so you can have the bot ignore you and not send an alert with "sp!mute" or "sp!ingore". We are also looking into the cooldown when the bot becomes more active.
