### ISSUE TITLE
Soothing role colour.

### ISSUE THREAD

**Issue by Lylythii** [Bobrobot1/Suicide-Prevention-Bot#24]
Been meaning to suggest this for a while.

If possible, the bot should auto-assign itself a role with the colour 'Baker Miller Pink'; which has been known to be a soothing/calming colour. The intent is that this would calm an individual in distress when the bot shows up.

`#FF91AF` *should* be an accurate colour hex for the shade of pink.
https://en.m.wikipedia.org/wiki/Baker-Miller_pink

**Comment by CactusKing101** [comment]
The problem with that is when the bot first joins the server discord auto assigns a role with the requested permissions.

**Comment by CactusKing101** [comment]
Especially because the bot only has the following perms.
![image](https://user-images.githubusercontent.com/44009236/131873238-5764b344-6c5f-4ded-a0a6-d3a4cc0e3a27.png)

**Comment by Lylythii** [comment]
I suppose this would require it to have some form of administrative powers, to allow it to create the new role.

**Comment by Lylythii** [comment]
Thanks for your response, I'm glad it's on the ToDo at the very least.

Would it be much to ask if (for the meantime) this was suggested to individuals who wish to add the bot to their servers, just a little "Hey, we thought this might be a nice addition on your behalf."? It not that's fine.

Best of luck!
