### ISSUE TITLE
Add some action commands like:

### ISSUE THREAD

**Issue by CatusKing** [Bobrobot1/Suicide-Prevention-Bot#34]
sp!hug
sp!kiss
sp!pat
etc.

perhaps get those GIFs that bots have

Edit: we could do it like https://spbot.ml/hugs/(number).gif and then get a random number

**Comment by CatusKing** [comment]
CAN I DO THIS IM BOREDD

**Comment by CPlusPatch** [comment]
Who's gonna stop you lmao go for it

**Comment by CPlusPatch** [comment]
Gotta use slash commands tho now

**Comment by CatusKing** [comment]
<3

**Comment by Killerjet101** [comment]
*never does it*

**Comment by CatusKing** [comment]
I WILL

**Comment by Killerjet101** [comment]
THEN DO IT

**Comment by Killerjet101** [comment]
Added
