### ISSUE TITLE
Replying to the bot with mentions on triggers response

### ISSUE THREAD

**Issue by Bobrobot1** [Bobrobot1/Suicide-Prevention-Bot#8]
Replying to the bot using the reply function, with @ enabled, triggers a bot response, as *technically*, you are mentioning the bot, add && function to the if statement requiring isReply to be false, or whatever it’s called.

**Comment by CactusKing101** [comment]
big 🧠 fixed 
`  if (message.mentions.has(client.user) && message.content.includes(client.user.id)) {
    message.channel.send(suicide);
  }`
so essentially when you @ someone it comes through as `<@664207565147865109>`
so when you reply it mentions you
but doesnt have the id in the content
so now we check for the bots id

**Comment by CactusKing101** [comment]
https://github.com/Bobrobot1/Suicide-Prevention-Bot/commit/00c0b34b87e112f5d3db282aa7b046eafb8818f3
btw
